/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 13 21:21:15 GMT 2021
 */

package org.apache.xml.security.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.xml.security.exceptions.AlgorithmAlreadyRegisteredException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AlgorithmAlreadyRegisteredException_ESTest extends AlgorithmAlreadyRegisteredException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AlgorithmAlreadyRegisteredException algorithmAlreadyRegisteredException0 = new AlgorithmAlreadyRegisteredException("");
      AlgorithmAlreadyRegisteredException algorithmAlreadyRegisteredException1 = new AlgorithmAlreadyRegisteredException(algorithmAlreadyRegisteredException0, (String) null);
      assertFalse(algorithmAlreadyRegisteredException1.equals((Object)algorithmAlreadyRegisteredException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AlgorithmAlreadyRegisteredException algorithmAlreadyRegisteredException0 = new AlgorithmAlreadyRegisteredException();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Object[] objectArray0 = new Object[0];
      AlgorithmAlreadyRegisteredException algorithmAlreadyRegisteredException0 = new AlgorithmAlreadyRegisteredException("gs=*u^D7rGH", objectArray0, (Exception) null);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AlgorithmAlreadyRegisteredException algorithmAlreadyRegisteredException0 = new AlgorithmAlreadyRegisteredException("");
      Object[] objectArray0 = new Object[0];
      AlgorithmAlreadyRegisteredException algorithmAlreadyRegisteredException1 = new AlgorithmAlreadyRegisteredException(algorithmAlreadyRegisteredException0, "org.apache.xml.security.exceptions.XMLSecurityException", objectArray0);
      assertFalse(algorithmAlreadyRegisteredException1.equals((Object)algorithmAlreadyRegisteredException0));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MockException mockException0 = new MockException();
      AlgorithmAlreadyRegisteredException algorithmAlreadyRegisteredException0 = new AlgorithmAlreadyRegisteredException("yQiKz'-n_]{T4XP", mockException0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Object[] objectArray0 = new Object[1];
      AlgorithmAlreadyRegisteredException algorithmAlreadyRegisteredException0 = new AlgorithmAlreadyRegisteredException("\nOriginal Exception was ", objectArray0);
  }
}
